approvals:
  minimum: 1
  ignore: pr_opener
  pattern: "^(👍|:\\+1:|:thumbsup:|:shipit:)$"
  veto:
    pattern: "^(👎|:-1:|:thumbsdown:)$"
  from:
    users:
      - adyachkov
      - dsorokin
      - dtscherwinka
      - rdecillo
      - lmontrieux
      - vstepanov
      - vgogichashvi
      - skamenskyi
      - yyankowski
X-Zalando-Team: "aruha"
X-Zalando-Type: code
