approvals:
  minimum: 2
  pattern: "^(👍|:\\+1:|:thumbsup:|:shipit:)$"
  veto:
    pattern: "^(👎|:-1:|:thumbsdown:)$"
  from:
    users:
      - adyach
      - antban
      - lmontrieux
      - rcillo
      - v-stepanov
      - valgog
      - SergKam
X-Zalando-Team: "aruha"
X-Zalando-Type: code
